# version: '3'

# services:
#   app:
#     build:
#       dockerfile: ./Dockerfile
#     image: posioappcr.azurecr.io/posio-app:latest

#     ports:
#       - 5000:5000
#     volumes:
#       - azurefileshare:/app/data

# volumes:
#   azurefileshare:

#     driver: azure_file
#     driver_opts:
#       share_name: sql-volume
#       storage_account_name: taskboardcrbaido

version: "3"

services:
  app:
    build:
      # dockerfile: ./Dockerfile
    image: posioappcr.azurecr.io/posio-app:latest
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: 2GB
    ports:
      - 5000:5000
    volumes:
      - azurefileshare:/app/data

volumes:
  azurefileshare:
    driver: azure_file
    driver_opts:
      share_name: posio-volume
      storage_account_name: posioappbigdo
